# Generated by Django 2.1 on 2020-02-15 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chofer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=400, null=True)),
                ('fechNacimiento', models.TextField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, max_length=100, null=True)),
                ('correo', models.TextField(blank=True, max_length=100, null=True)),
                ('telCasa', models.TextField(blank=True, max_length=100, null=True)),
                ('telCelular', models.TextField(blank=True, max_length=100, null=True)),
                ('urlQr', models.TextField(blank=True, max_length=100, null=True)),
                ('foto', models.FileField(blank=True, help_text='Fotografía', null=True, upload_to='', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'chofer',
                'verbose_name_plural': 'choferes',
                'db_table': 'chofer',
            },
        ),
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaFinal', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_chofer', models.ForeignKey(db_column='fk_chofer', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_bus.chofer', verbose_name='fk_chofer')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=200, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(blank=True, max_length=200, null=True)),
                ('longitud', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='seguiminento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fk_chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bus.chofer', verbose_name='fk_chofer')),
                ('fk_ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bus.ruta', verbose_name='fk_ruta')),
            ],
            options={
                'verbose_name': 'seguimiento',
                'verbose_name_plural': 'seguimientos',
            },
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccionInicial', models.CharField(blank=True, max_length=400, null=True)),
                ('latitudInicial', models.CharField(blank=True, max_length=200, null=True)),
                ('longitudInicial', models.CharField(blank=True, max_length=200, null=True)),
                ('direccionFinal', models.CharField(blank=True, max_length=400, null=True)),
                ('latitudFinal', models.CharField(blank=True, max_length=200, null=True)),
                ('longitudFinal', models.CharField(blank=True, max_length=200, null=True)),
                ('solicitudEspecial', models.CharField(blank=True, max_length=200, null=True)),
                ('programacionViaje', models.CharField(blank=True, max_length=200, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_bus.Profile', verbose_name='fk_usuario')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'db_table': 'solicitud',
            },
        ),
        migrations.AddField(
            model_name='seguiminento',
            name='fk_solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bus.solicitud', verbose_name='fk_solicitud'),
        ),
    ]
