# Generated by Django 2.1 on 2020-02-15 10:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='foto',
            field=models.FileField(blank=True, help_text='Forografía', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\xampp\\htdocs\\buses\\static/fotos'), upload_to='', verbose_name='Orchivo'),
        ),
    ]
