# Generated by Django 2.1 on 2020-02-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0002_auto_20200215_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
