# Generated by Django 2.1 on 2020-02-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0004_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
