# Generated by Django 2.1 on 2020-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0007_auto_20200215_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fk_usuario',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
