# Generated by Django 2.1 on 2020-02-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0008_auto_20200215_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
