# Generated by Django 2.1 on 2020-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus', '0009_auto_20200218_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudFormulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(blank=True, max_length=400, null=True)),
                ('direccionActual', models.CharField(blank=True, max_length=600, null=True)),
                ('direccionFinal', models.CharField(blank=True, max_length=600, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('horaSolicitud', models.DateTimeField(blank=True, null=True)),
                ('horaAtencion', models.DateTimeField(blank=True, null=True)),
                ('requerimientosAdicionales', models.CharField(blank=True, max_length=600, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'solicitudFormulario',
                'verbose_name_plural': 'solicitudesFormulario',
                'db_table': 'solicitudFormulario',
            },
        ),
    ]
